<script type="text/javascript">
    var mymo_cfg = {
        "act": "",
        "post_url": "<?php echo mymo_get_current_url() ?>",
        "ajax_url": "<?php echo admin_url('admin-ajax.php') ?>",
        "loading_img": "<?php echo esc_url(get_template_directory_uri() . '/assets/images/ajax-loader.gif') ?>",
        "eps_slug": "eps",
        "server_slug": "s",
        "type_slug": "slug-2",
        "post_title": "<?php echo $title ?>",
        "post_id": '<?php echo isset($is_watch) ? $post_id : '' ?>',
        "episode_slug": "",
        "server": 1,
        "player_error_detect": "display_modal",
        "paging_episode": "false",
        "episode_display": "show_list_eps",
        "episode_nav_num": 100,
        "auto_reset_cache": true,
        "resume_playback": true,
        "resume_text": "<?php echo __('Automatically replay the movie', 'mymo') ?>",
        "resume_text_2": "<?php echo __('Replay from begin', 'mymo') ?>",
        "playback": "<?php echo __('Playback', 'mymo') ?>",
        "continue_watching": "<?php echo __('Continue watching', 'mymo') ?>",
        "player_reload": "<?php echo __('Player reload', 'mymo') ?>",
        "jw_error_msg_0": "",
        "jw_error_msg_1": "<?php echo __('Video error can not be played.', 'mymo') ?>",
        "jw_error_msg_2": "<?php _e('To continue watching, please click Reload Player button', 'mymo') ?>",
        "jw_error_msg_3": "<?php echo __('or click on buttons listed below', 'mymo') ?>",
        "light_on": "<?php echo __('Light on', 'mymo') ?>",
        "light_off": "<?php echo __('Light off', 'mymo') ?>",
        "expand": "<?php echo __('Expand', 'mymo') ?>",
        "collapse": "<?php echo __('Collapse', 'mymo') ?>",
        "player_loading": "<?php echo __('Player loading', 'mymo') ?>",
        "player_autonext": "<?php echo __('Player autonext', 'mymo') ?>",
        "is_adult": false,
        "adult_title": "<?php echo __('Adult Content Warning!', 'mymo') ?>",
        "adult_content": "",
        "show_only_once": "<?php echo __('Show only once', 'mymo') ?>",
        "exit_btn": "<?php echo __('Exit', 'mymo') ?>",
        "is_18plus": "",
        "report_lng": {
            "title": "<?php echo $title ?>",
            "alert": "",
            "msg": "<?php echo __('Content', 'mymo') ?>",
            "msg_success": "<?php echo __('Thank you for submitting error message. We will fix errors as soon as possible', 'mymo') ?>",
            "loading_img": "<?php echo esc_url(get_template_directory_uri() . '/assets/images/loading.gif') ?>",
            "report_btn": "<?php echo __('Report', 'mymo') ?>",
            "name_or_email": "<?php echo __('Name', 'mymo') ?>",
            "close": "<?php echo __('Close', 'mymo') ?>"
        }
    }
</script>